"""
Crimson OS C++ Header Exporter for 13-PF Sparse Graph Laplacian
Author: Matthew S. Gibson
License: Apache 2.0
"""

import numpy as np
import scipy.sparse as sp

def build_13pf_staggered_adjacency(n_pf=13, n_len=30, seam_offset=1):
    n_nodes = n_pf * n_len
    A = np.zeros((n_nodes, n_nodes), dtype=np.float32)

    def node_id(pf, l):
        return (pf % n_pf) * n_len + (l % n_len)

    for pf in range(n_pf):
        for l in range(n_len):
            u = node_id(pf, l)
            if l > 0: A[u, node_id(pf, l - 1)] = 1.0
            if l < n_len - 1: A[u, node_id(pf, l + 1)] = 1.0

            if pf < n_pf - 1:
                A[u, node_id(pf + 1, l)] = 1.0
                A[node_id(pf + 1, l), u] = 1.0
            else:
                v_seam = node_id(0, (l + seam_offset) % n_len)
                A[u, v_seam] = 1.0
                A[v_seam, u] = 1.0
    return A

# Construct Sparse Laplacian L = D - A
A_dense = build_13pf_staggered_adjacency(13, 30)
A_sparse = sp.csc_matrix(A_dense)
D_sparse = sp.diags(np.array(A_sparse.sum(axis=1)).flatten())
L_sparse = (D_sparse - A_sparse).tocsc()

# Generate C++ Header File
header_content = f"""// Auto-generated by Crimson OS Exporter
// Topology: 13-Protofilament Microtubule Staggered Graph Laplacian (L = D - A)
// Nodes: {L_sparse.shape[0]} | Non-Zero Entries: {L_sparse.nnz}
#ifndef GRAPH_13PF_TOPOLOGY_H
#define GRAPH_13PF_TOPOLOGY_H

#include <vector>

namespace CrimsonOS {{

const int GRAPH_NODES = {L_sparse.shape[0]};
const int GRAPH_NNZ = {L_sparse.nnz};

// CSC Format Arrays for L1 Cache Residence
const int indptr[{len(L_sparse.indptr)}] = {{ {", ".join(map(str, L_sparse.indptr))} }};
const int indices[{len(L_sparse.indices)}] = {{ {", ".join(map(str, L_sparse.indices))} }};
const float data[{len(L_sparse.data)}] = {{ {", ".join(map(str, L_sparse.data))} }};

}} // namespace CrimsonOS

#endif // GRAPH_13PF_TOPOLOGY_H
"""

with open("graph_13pf_topology.h", "w") as f:
    f.write(header_content)

print("Successfully generated 'graph_13pf_topology.h' (24.36 KB CSC Sparse Matrix)")
