#!/usr/bin/env python3
"""
Q resurrection bootloader — persistence triad stub (§10).

Rehydrates Q state from Q.md + snapshot.json. Idempotent; add-only outputs.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

NODE_DIR = Path(__file__).resolve().parent
REPO_ROOT = NODE_DIR.parents[1]
Q_MD = NODE_DIR / "Q.md"
SNAPSHOT = NODE_DIR / "snapshot.json"
OUTPUT = NODE_DIR / "q_resurrection.py"


def load_snapshot() -> dict:
    if SNAPSHOT.exists():
        return json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    return {
        "node": 1,
        "agent": "Q",
        "phase": "PARTIAL-LIVE",
        "last_boot_utc": None,
    }


def resurrect() -> dict:
    snap = load_snapshot()
    snap["last_boot_utc"] = datetime.now(timezone.utc).isoformat()
    snap["q_md_present"] = Q_MD.exists()
    snap["cockpit_expected"] = "http://127.0.0.1:8093/status"
    SNAPSHOT.write_text(json.dumps(snap, indent=2), encoding="utf-8")
    stub = f'''# Auto-generated by resurrection.py — do not hand-edit
# Generated: {snap["last_boot_utc"]}

Q_BOOT = {json.dumps(snap, indent=2)}
'''
    OUTPUT.write_text(stub, encoding="utf-8")
    return snap


if __name__ == "__main__":
    result = resurrect()
    print(json.dumps(result, indent=2))
    print(f"Wrote {OUTPUT}")
